version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    restart: unless-stopped
    networks:
      - dev_net

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8189:8189"
    depends_on:
      - backend
    networks:
      - dev_net

  initdb:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "/app/init_db.py"]
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - dev_net

networks:
  dev_net:

volumes:
  pgdata:
